// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDDyon3xTREqiHrlK35YyaTYKNkElj-B4',
    appId: '1:980608348067:android:29c5aa12b20d9c04f8f416',
    messagingSenderId: '980608348067',
    projectId: 'selective-collect-dev',
    storageBucket: 'selective-collect-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJudmfmOlVG2qFAXfN4XAwgw07oOOaQOo',
    appId: '1:980608348067:ios:c64f6fba84bae283f8f416',
    messagingSenderId: '980608348067',
    projectId: 'selective-collect-dev',
    storageBucket: 'selective-collect-dev.appspot.com',
    iosClientId: '980608348067-n3gng21b0bjrdd8svmpsr4u6onvvsosp.apps.googleusercontent.com',
    iosBundleId: 'com.selective.collect.selectiveCollect',
  );
}
